version: '3.8'

services:

  blockscout:
    depends_on:
      - db
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        COIN: ""
    restart: always
    container_name: 'blockscout'
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    ports:
      - 4000:4000

  letsencrypt:
    depends_on:
      - blockscout
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    restart: always
    volumes:
      - ./config:/config
      - ./default:/config/nginx/site-confs/default
    environment:
      - EMAIL=hussain@peaq.io
      - URL=scout.test.peaq.network
      - VALIDATION=http
      - TZ=Europe/Berlin
      - PUID=500
      - PGID=500
    ports:
      - "443:443"
      - "80:80"